// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
)

type Student struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Age       int32     `json:"age"`
	GroupName string    `json:"group_name"`
}
