// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateStudents(ctx context.Context, arg CreateStudentsParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
