// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student.sql

package db

import (
	"context"
)

const createStudents = `-- name: CreateStudents :one
INSERT INTO students(
    full_name, age, group_name
) VALUES (
    $1, $2, $3
) RETURNING id, full_name, age, group_name
`

type CreateStudentsParams struct {
	FullName  string `json:"full_name"`
	Age       int32  `json:"age"`
	GroupName string `json:"group_name"`
}

func (q *Queries) CreateStudents(ctx context.Context, arg CreateStudentsParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudents, arg.FullName, arg.Age, arg.GroupName)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Age,
		&i.GroupName,
	)
	return i, err
}
